In [3]:
import sys
!{sys.executable} -m pip install numpy

In [4]:
import numpy as np

# Task 1 _Variant 9_

### Excercise 1. 
Enter the number n. Output an array of size nхn, in which the
diagonals are numbers from 1 to n, and other elements are 0

In [5]:
try:
    n = int(input("Enter size of matrix nxn: "))
    diag = np.arange(1,n+1,1)
    print(np.diag(diag))
except:
    print("Error")

Enter size of matrix nxn: 6
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


### Excercise 2. 
Enter the number n. Arrange 1 and 0 in a checkerboard pattern,
starting with 0 in a matrix of size nхn, using slicing.

In [34]:
try:
    n = int(input("Enter size of matrix nxn: "))
    arr = np.zeros((n,n), dtype=int)
    arr[1::2,::2] = 1
    arr[::2,1::2] = 1
    print(arr)
except:
    print("Error")

Enter size of matrix nxn: 4
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


### Excercise 4. 
Enter the numbers n and m. Output an array of size nхm, in which the
first line (line with zero index) are numbers from 0 to m-1, and all other elements
of the matrix are equal to 0.

In [11]:
try:
    n, m = [int(i) for i in input('Enter size of matrix nxm: ').split()]
    x = np.arange(n*m)
    x = x.reshape(n, m)
    x[1::, ::] = 0
    print(x)
except:
    print("Error")

Enter size of matrix nxm: 4 3
[[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


### Excercise 7. 
An array is entered from the keyboard. Replace all zeros with -1.

In [14]:
try:
    arr = np.array(input("Enter array elements ").split(), dtype =int)
    arr[arr==0]=-1
    print(arr)
except:
    print("Error")

Enter array elements 5 4 000 8 0 0 5
[ 5  4 -1  8 -1 -1  5]


### Excercise 8.
An array is entered from the keyboard. Count the number of zero and
non-zero elements in it.


In [15]:
try:
    arr = np.array(input("Enter array elements ").split(), dtype =int)
    print("Zero elements: ", len(arr[arr==0]))
    print("Non-zero elements: ", len(arr[arr!=0]))
except:
    print("Error")

Enter array elements 8 0 6 4 000 0 7 0
Zero elements:  4
Non-zero elements:  4


### Excercise 12.
Create an array of 1 of size nхn and create an inside "border" formed
from 0.

In [17]:
try:
    n = int(input("Enter size of matrix nxn: "))
    arr = np.full((n,n), 1.)
    arr[0]=0.
    arr[-1]=0.
    arr[:,0]=0.
    arr[:,-1]=0.
    print(arr)
except:
    print("Error")

Enter size of matrix nxn: 6
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


### Excercise 13. 
Determine the index of 70-th element in a vector, if it is converted
into a matrix of size 4x5x6.

In [19]:
try:
    n = 4
    m = 5
    k = 6
    h = 70-1
    x = (h // (m*k), (h % (m*k))//k, (h % (m*k)) % k)
    print('In matrix {}х{}х{} index of {} element : {}'.format(n, m, k, h+1, str(x)))
except:
    print("Error")

In matrix 4х5х6 index of 70 element : (2, 1, 3)


### Excercise 15.
Arrange 1 and 0 on the 8х8 field in a checkerboard pattern.

In [21]:
try:
    x = np.ones((3,3))
    print("Checkerboard pattern:")
    x = np.zeros((8,8),dtype=int)
    x[1::2,::2] = 1
    x[::2,1::2] = 1
    print(x)
except:
    print("Error")

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Excercise 16.
Fill the even columns of the matrix of nхn size with 1, and the odd
ones with 0.

In [23]:
try:
    n = int(input("Enter size of matrix nxn: "))
    arr = np.zeros((n,n), dtype=int)
    arr[::,1::2]=1
    print(arr)
except:
    print("Error")

Enter size of matrix nxn: 4
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


### Excercise 20. 
Generate a vector of n elements that are evenly spaced on the
interval (0,1) i.e. both ends of the interval are not included. Output values up to 3
decimal places.


In [27]:
try:
    n = int(input("Enter size of vector: "))
    print(np.around(np.linspace(0, 1, n+2, dtype=float),3)[1:-1:])
except:
    print("Error")

Enter size of vector : 10
[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]


# Task 2 Variant 9

### 2. Solve the system of linear equations using Cramer's formulas and perform a test using:
 a) matrix multiplication;
 b) numpy.linalg.solve().


$$\left\{\begin{matrix}
 x_{1}+2x_{2}+x_{3}+x_{4}=8 \\ 
 2x_{1}+x_{2}+x_{3}+x_{4}=5 \\ 
 x_{1}-x_{2}+2x_{3}+x_{4}=-1\\ 
 x_{1}+x_{2}-x_{3}+3x_{4}=10\\
\end{matrix}\right.$$

In [33]:
def solve_by_cramer(mA, b):
    n = mA.shape[0]
    det = np.linalg.det(mA)
    xs = np.empty(n)
    if det == 0:
        return None
    for i in range(n):
        mAi = np.copy(mA)
        mAi[:, i] = b
        xs[i] = np.linalg.det(mAi) / det
    return xs

a = np.array([[1,2,1,1],
              [2,1,1,1],
              [1,-1,2,1],
              [1,1,-1,3]])
b = np.array([8,5,-1,10])
roots = solve_by_cramer(a, b)
print(roots)
print(np.linalg.solve(a,b))
ax = np.dot(a,roots)
print(ax)
print(np.allclose(ax, b))

[-0.05263158  2.94736842 -0.15789474  2.31578947]
[-0.05263158  2.94736842 -0.15789474  2.31578947]
[ 8.  5. -1. 10.]
True


### 3. Calculate the value of the matrix expression.

$$\mathit{2A-(A^{2}+B)B), A=\begin{pmatrix}
1 & 4 & 2\\ 
2 & 1  &-2 \\ 
0 & 1 & -1
\end{pmatrix}, B=\begin{pmatrix}
4 & 6  & -2\\ 
4 & 10 & 1\\ 
2 & 4 & -5 
\end{pmatrix}}$$

In [29]:
A = np.array([[1, 4, 2], [2, 1, -2], [0, 1, -1]], dtype=int)
B = np.array([[4, 6, -2], [4, 10, 1], [2, 4, -5]], dtype=int)
2*A-(A**2+B)*B

array([[ -18, -124,    8],
       [ -28, -108,   -9],
       [  -4,  -18,  -22]])

### 4. Solve the matrix equation using an inverse matrix and perform a test using:
 a) matrix multiplication;
 b) numpy.linalg.solve().

$$\begin{pmatrix}
2 & 2 &-5 \\ 
 4& 2  &0 \\ 
1 & 1 &2 
\end{pmatrix}\mathit{* X =\begin{pmatrix}
 -1& 2 & 4\\ 
 0& 3 & 2\\ 
-1 &-3  & 4
\end{pmatrix}}$$

In [30]:
coef_matrix = np.array([[2,2,-5],
                       [4,2,0],
                       [1,1,2]])
b2_matrix = np.array([[-1,2,4],
                     [0,3,2],
                     [-1,-3,4]])
inverse_matrix = np.linalg.inv(coef_matrix)
x_matrix = inverse_matrix.dot(b2_matrix)
print("X array:\n ",np.round(x_matrix),"\n")
print("Linalg check: \n",np.round(np.linalg.solve(coef_matrix,b2_matrix)),"\n")
print("Multiplication check: \n",np.round(coef_matrix.dot(x_matrix)))

X array:
  [[ 1.  3. -2.]
 [-2. -4.  5.]
 [-0. -1.  0.]] 

Linalg check: 
 [[ 1.  3. -2.]
 [-2. -4.  5.]
 [-0. -1.  0.]] 

Multiplication check: 
 [[-1.  2.  4.]
 [ 0.  3.  2.]
 [-1. -3.  4.]]
